version: "3.9"

services:
  db:
    image: postgres:15
    container_name: order-service-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - order_service_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    networks: [fastfood]

  migrations:
    build: .
    container_name: order-service-migrations
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: alembic upgrade head
    volumes:
      - .:/app
    networks: [fastfood]

  web:
    build: .
    container_name: order-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    networks: [fastfood]

volumes:
  order_service_db_data:

networks:
  fastfood:
    external: true
    name: fastfood-net